# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SubAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Account')),
            ],
        ),
        migrations.CreateModel(
            name='SubSubAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('subAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.SubAccount')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Account.AccountCategory'),
        ),
    ]
